config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    get :favorites, on: :collection
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'

  resources :users, only: [:index, :show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
    member do
      get :followings, :followers
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower_relationship, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy #フォロー取得（フォローする側から見て、フォローされる側のユーザーを集める）
  has_many :following_user, through: :follower_relationship, source: :followed #中間テーブルを介して「followed」モデルのユーザー（フォローされた側）を集めることを「following_user」と定義

  has_many :followed_relationship, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #フォロワー取得（フォローされる側から見て、フォローしてくる側のユーザーを集める）
  has_many :follower_user, through: :followed_relationship, source: :follower #中間テーブルを介して「follower」モデルのユーザー（フォローする側）を集めることを「follower_user」と定義


  attachment :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    followed_relationship.find_by(follower_id: user.id).present?
  end
  # # ユーザをフォローする
  # def follow(user_id)
  #   follower.create(followed_id: user.id)
  # end
  # # ユーザーのフォローを解除
  # def unfollow(user_id)
  #   follower.find_by(followed_id: user.id).destroy
  # end
  # # フォローしていればtrueを返す
  # def following?(user)
  #   following_user.include?(user)
  # end

  def self.search(search,word)
    if search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
      @user = User.where(name: word)
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user

  def index
    @users = User.all
    @book = Book.new
    # @relationship = @user.following.find_by(follower_id: current_user.id)
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def followings
    # @followings = @user.following_users
    user = User.find(params[:id])
    @users = user.following_user
  end

  def followers
    # @followers = @user.follower_users
    user = User.find(params[:id])
    @users = user.follower_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  # def set_user
  #   @user = User.find(params[:id])
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<p></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>User info</h1>
      <% if @user.errors.any? %>
        <%= @user.errors.count %>errors prohibited this obj from being saved:
        <% @user.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="inputName">Name</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="inputImage">Image</label><br>
          <%= f.attachment_field :profile_image %>
        </div>
        <div class="form-group">
          <label for="inputIntroduction">Introduction</label>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class:"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
  <% if @users.count == 0 %>
    <p>ユーザーはいません</p>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <% @users.each do |user| %>
      <tbody>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', size: '40x40',  fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td>フォロー数:<%= user.following_user.count  %></td>
          <td>フォロワー数:<%= user.follower_user.count %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  <% end %>

app/views/users/followings.html.erb
<h2>Follow Users</h2>
  <% if @users.count == 0 %>
    <p>ユーザーはいません</p>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <% @users.each do |user| %>
      <tbody>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', size: '40x40',  fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td>フォロー数:<%= user.following_user.count  %></td>
          <td>フォロワー数:<%= user.follower_user.count %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  <% end %>

app/views/users/index.html.erb
<% if flash[:notice] %>
  <p class="notice">
    <%= flash[:notice] %>
　</p>
<% end %>
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <%= render 'books/list', book: @book, user: current_user %>
        </div>

        <div class="col-md-8 offset-md-1">
            <h2>Users</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th>image</th>
                            <th>name</th>
                            <th colspan="6"></th>
                        </tr>
                    </thead>
                    <% @users.each do |user| %>
                    <tbody>
                        <tr>
                            <td>
                                <%= attachment_image_tag user, :profile_image, format: 'jpeg', size: '40x40',  fallback: "no_image.jpg" %>
                            </td>
                            <td>
                                <%= user.name %>
                            </td>
                            <td>フォロー数:<%= user.following_user.count  %></td>
                            <td>フォロワー数:<%= user.follower_user.count %></td>
                            <td>
                              <% if current_user != user %>
                                <% if user.followed_by?(current_user) %>
                                  <p><%=link_to "フォロー外す", user_relationship_path(user_id: user, id: user), method: :delete %></p>
                                <% else %>
                                  <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
                                <% end %>
                              <% end %>
                            </td>
                            <td>
                                <%= link_to "Show", user_path(user.id) %>
                            </td>
                        </tr>
                    </tbody>
                    <% end %>
                </table>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <p class="notice">
    <%= flash[:notice] %>
　</p>
<% end %>
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <%= render 'books/list', book: @book, user: @user %>
        </div>
        
        <div class="col-md-8 offset-md-1">
            <h2>Books</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                        <th colspan="4"></th>
                    </tr>
                </thead>
                <% @books.each do |book| %>
                <tbody>
                    <tr>
                        <td>
                          <%= link_to user_path(book.user.id) do %>
                            <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', size: '40x40',  fallback: "no_image.jpg" %>
                          <% end %>
                        </td>
                        <td>
                          <%= link_to book.title, book_path(book.id) %>
                        </td>
                        <td>
                          <%= book.body %>
                        </td>
                        <td>
                          コメント数:<%= book.book_comments.count %>
                        </td>
                    </tr>
                </tbody>
                <% end %>
            </table>
            <%= paginate @books %>
        </div>
    </div>
</div>