config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    get :favorites, on: :collection
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'

  resources :users, only: [:index, :show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
    member do
      get :followings, :followers
    end
  end

end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def self.search(search, word)
    if search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
      @book = Book.where(title: word)
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = "You have updated book successfully."
     redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
    	  <th>name</th>
    	  <th><%= user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th><%= link_to (user.following_user.count), followings_user_path(user.id) %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%= link_to (user.follower_user.count), followers_user_path(user.id) %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
      <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
          <%=link_to "フォロー外す", user_relationship_path(user_id: user, id: user), method: :delete, class:"btn btn-success" %>
        <% else %>
          <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-success" %></p>
        <% end %>
      <% else %>
        <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
        <% end %>
      <% end %>
  </div>

  <h2 class="mt-3">New book</h2>
  <%= form_with model: book, local:true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class:"form-control" %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book', class:"btn btn-success" %>
      </div>
  <% end %>

app/views/books/edit.html.erb
<p></p>
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <h1>Editing Book</h1>
            <% if @book.errors.any? %>
              <%= @book.errors.count %>errors prohibited this obj from being saved:
              <% @book.errors.full_messages.each do |message| %>
                <%= message %>
              <% end %>
            <% end %>
            <%= form_with model: @book, local:true do |f| %>
                <div class="form-group">
                    <label for="book_title">Title</label>
                    <%= f.text_field :title, class: "form-control" %>
                </div>
                <div class="form-group">
                    <label for="book_opinion">Opinion</label>
                    <%= f.text_area :body, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.submit 'Update Book', class: "btn btn-success" %>
                </div>
            <% end %>
            <%= link_to "Show", book_path(@book) %>
            |
            <%= link_to "Back", books_path %>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<% if flash[:notice] %>
  <p class="notice">
    <%= flash[:notice] %>
　</p>
<% end %>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
        <%= render 'books/list', book: @book, user: current_user %>
    </div>

    <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="5"></th>
            </tr>
          </thead>
          <% @books.each do |book| %>
            <tbody>
              <tr>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                    <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', size: '40x40',  fallback: "no_image.jpg" %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book.title, book_path(book.id) %>
                </td>
                <td>
                  <%= book.body %>
                </td>
                <td>
                  <div id="favorite-btn_<%= book.id %>">
                    <%= render partial: 'favorites/favorite-btn', locals: {book: book} %>
                  </div>
                </td>
                <td>コメント数:<%= book.book_comments.count %></td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p class="notice-user-update">
    <%= flash[:notice] %>
　</p>
<% end %>
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <%= render 'books/list', book: @book_new, user: @book.user %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Book detail</h2>
          <table class="table">
            <tbody>
              <tr>
                <td>
                  <%= link_to user_path(@book.user.id)do %>
                    <%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', size: '40x40',  fallback: "no_image.jpg" %><br>
                    <%= @book.user.name %>
                  <% end %>
                </td>
                <td><%= link_to @book.title, book_path %></td>
                <td><%= @book.body %></td>
                <td>
                  <div id="favorite_btn_<%= @book.id %>">
                    <%= render partial: 'favorites/favorite-btn', locals: {book: @book} %>
                  </div>
                </td>
                <td>コメント数:<%= @book.book_comments.count %></td>
                <% if @book.user == current_user %>
                  <td>
                    <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
                  </td>
                  <td>
                    <%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %>
                  </td>
                <% end %>
              </tr>
            </tbody>
          </table>
          <table id="comment">
            <%= render 'book_comments/index', book: @book,book_comment: @book_comment %>
          
          <%= form_with model:[@book, @book_comment] do |f| %>
            <%= f.text_area :comment, size: '91x5'%>
            <%= f.submit '送信' %>
          <% end %>
          
        </div>